  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus - quarkusfunqylambda-1.0.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    Quarkusfunqylambda:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.funqy.lambda.FunqyStreamHandler::handleRequest
        Runtime: java11
        CodeUri: ../build/function.zip
        MemorySize: 256
        Timeout: 15
        Policies: AWSLambdaBasicExecutionRole