  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus - quarkusfunqylambda-1.0.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    Quarkusfunqylambda:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.funqy.lambda.FunqyStreamHandler::handleRequest
        Runtime: java11
        CodeUri: ../build/function.zip
        MemorySize: 256
        Timeout: 15
        Policies:
          - AWSLambdaBasicExecutionRole
          - AWSLambdaDynamoDBExecutionRole
        Events:
          DynamoDBStream:
            Type: DynamoDB
            Properties:
              BatchSize: 1
              StartingPosition: TRIM_HORIZON
              Stream: "arn:aws:dynamodb:eu-central-1:976076171170:table/vankog-funqy-books/stream/2021-05-03T12:19:39.173"